# # This file is the entry point to configure your own services.
# # Files in the packages/ subdirectory configure your dependencies.

# # Put parameters here that don't need to change on each machine where the app is deployed
# # https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
# parameters:
# cv_upload_dir: '%kernel.project_dir%/public/uploads/cvs'
# services:
#     # default configuration for services in *this* file
#     _defaults:
#         autowire: true      # Automatically injects dependencies in your services.
#         autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

#     # makes classes in src/ available to be used as services
#     # this creates a service per class whose id is the fully-qualified class name
#     App\:
#         resource: '../src/'
#         exclude:
#             - '../src/DependencyInjection/'
#             - '../src/Entity/'
#             - '../src/Kernel.php'

#     # add more service definitions when explicit configuration is needed
#     # please note that last definitions always *replace* previous ones
# config/services.yaml
parameters:
    upload_directory: '%kernel.project_dir%/public/uploads/profile_pictures'
    groups_images_directory: '%kernel.project_dir%/public/uploads/groups'
    cv_upload_dir: '%kernel.project_dir%/public/uploads/cvs'
    mercure_jwt_secret: '%env(MERCURE_JWT_SECRET)%'
    mercure_hub_url: 'http://localhost:3000/.well-known/mercure'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            string $ollamaApiUrl: '%env(OLLAMA_API_URL)%'
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
